// GENERATED by scripts/inline-migrations.ts — do not edit.
//
// Source of truth is src/schema.drizzle.ts (tables, via drizzle-kit generate) plus
// the hand-written custom migrations under migrations/ (triggers, which drizzle-kit
// does not model). Regenerate with:
//
//   pnpm --filter @holiday/store-postgres run migrations:build
//
// This exists because the CLI ships as one self-contained file: Drizzle's migrate()
// reads .sql off disk at runtime, and there is no disk to read next to a bundled
// plugin binary.

export interface InlinedMigration {
  readonly name: string;
  /** sha256 of the raw migration.sql. Editing an applied migration is detected. */
  readonly hash: string;
  readonly statements: readonly string[];
}

export const MIGRATIONS: readonly InlinedMigration[] = [
  {
    "name": "20260717115119_init",
    "hash": "97636cf49ca567e61196c79dd9f18eb4fc564b660afe49494de90be9ac5ff937",
    "statements": [
      "CREATE TABLE \"account\" (\n\t\"id\" text PRIMARY KEY,\n\t\"code\" text NOT NULL UNIQUE,\n\t\"type\" text NOT NULL,\n\t\"parent_id\" text,\n\t\"commodity\" text,\n\t\"monetary\" integer DEFAULT 1 NOT NULL,\n\t\"cash\" integer DEFAULT 0 NOT NULL,\n\t\"placeholder\" integer DEFAULT 0 NOT NULL,\n\t\"opened_on\" text NOT NULL,\n\t\"closed_on\" text,\n\tCONSTRAINT \"account_type_enum\" CHECK (\"type\" IN ('asset','liability','equity','income','expense')),\n\tCONSTRAINT \"account_monetary_bool\" CHECK (\"monetary\" IN (0,1)),\n\tCONSTRAINT \"account_cash_bool\" CHECK (\"cash\" IN (0,1)),\n\tCONSTRAINT \"account_placeholder_bool\" CHECK (\"placeholder\" IN (0,1))\n);",
      "CREATE TABLE \"audit_log\" (\n\t\"seq\" integer PRIMARY KEY,\n\t\"at\" text NOT NULL,\n\t\"event\" text NOT NULL,\n\t\"subject\" text NOT NULL,\n\t\"detail\" text DEFAULT '{}' NOT NULL,\n\t\"prev_hash\" text NOT NULL,\n\t\"hash\" text NOT NULL UNIQUE\n);",
      "CREATE TABLE \"balance_assertion\" (\n\t\"id\" text PRIMARY KEY,\n\t\"account_id\" text NOT NULL,\n\t\"as_of\" text NOT NULL,\n\t\"commodity\" text NOT NULL,\n\t\"expected_minor\" bigint NOT NULL,\n\t\"note\" text,\n\t\"created_at\" text NOT NULL\n);",
      "CREATE TABLE \"book\" (\n\t\"id\" text PRIMARY KEY,\n\t\"schema_version\" integer NOT NULL,\n\t\"functional_currency\" text NOT NULL,\n\t\"close_grain\" text DEFAULT 'month' NOT NULL,\n\t\"timezone\" text DEFAULT 'Asia/Seoul' NOT NULL,\n\t\"dedupe_key_version\" integer DEFAULT 1 NOT NULL,\n\t\"fx_max_staleness_days\" integer DEFAULT 7 NOT NULL,\n\t\"created_at\" text NOT NULL,\n\tCONSTRAINT \"book_singleton\" CHECK (\"id\" = 'book'),\n\tCONSTRAINT \"book_close_grain_enum\" CHECK (\"close_grain\" IN ('day','week','month','quarter','year'))\n);",
      "CREATE TABLE \"card\" (\n\t\"account_id\" text PRIMARY KEY,\n\t\"funding_account_id\" text NOT NULL,\n\t\"cycle_close_day\" integer NOT NULL,\n\t\"payment_month_offset\" integer NOT NULL,\n\t\"payment_day\" integer NOT NULL,\n\t\"label\" text,\n\tCONSTRAINT \"card_close_day_range\" CHECK (\"cycle_close_day\" BETWEEN 1 AND 31),\n\tCONSTRAINT \"card_offset_range\" CHECK (\"payment_month_offset\" BETWEEN 0 AND 3),\n\tCONSTRAINT \"card_payment_day_range\" CHECK (\"payment_day\" = -1 OR \"payment_day\" BETWEEN 1 AND 31)\n);",
      "CREATE TABLE \"command_log\" (\n\t\"idem_key\" text PRIMARY KEY,\n\t\"request_sha256\" text NOT NULL,\n\t\"response_json\" text NOT NULL,\n\t\"created_at\" text NOT NULL\n);",
      "CREATE TABLE \"commodity\" (\n\t\"code\" text PRIMARY KEY,\n\t\"exponent\" integer NOT NULL,\n\t\"kind\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\tCONSTRAINT \"commodity_exponent_range\" CHECK (\"exponent\" BETWEEN 0 AND 9),\n\tCONSTRAINT \"commodity_kind_enum\" CHECK (\"kind\" IN ('fiat','crypto','security','unit'))\n);",
      "CREATE TABLE \"fx_rate\" (\n\t\"id\" text PRIMARY KEY,\n\t\"as_of\" text NOT NULL,\n\t\"base\" text NOT NULL,\n\t\"quote\" text NOT NULL,\n\t\"rate\" text NOT NULL,\n\t\"source\" text NOT NULL,\n\t\"fetched_at\" text NOT NULL\n);",
      "CREATE TABLE \"ingest_batch\" (\n\t\"id\" text PRIMARY KEY,\n\t\"source_sha256\" text NOT NULL UNIQUE,\n\t\"source_name\" text,\n\t\"submitted_at\" text NOT NULL,\n\t\"item_count\" integer DEFAULT 0 NOT NULL,\n\tCONSTRAINT \"ingest_batch_count_nonneg\" CHECK (\"item_count\" >= 0)\n);",
      "CREATE TABLE \"ingest_item\" (\n\t\"id\" text PRIMARY KEY,\n\t\"batch_id\" text NOT NULL,\n\t\"dedupe_key\" text NOT NULL,\n\t\"dedupe_authority\" text NOT NULL,\n\t\"external_ref\" text,\n\t\"merchant\" text,\n\t\"txn_id\" text,\n\t\"status\" text DEFAULT 'pending' NOT NULL,\n\t\"reason\" text,\n\t\"parsed_json\" text NOT NULL,\n\t\"created_at\" text NOT NULL,\n\tCONSTRAINT \"ingest_item_status_enum\" CHECK (\"status\" IN ('pending','accepted','rejected')),\n\tCONSTRAINT \"ingest_item_authority_enum\" CHECK (\"dedupe_authority\" IN ('image','external_ref','natural'))\n);",
      "CREATE TABLE \"installment\" (\n\t\"id\" text PRIMARY KEY,\n\t\"card_account_id\" text NOT NULL,\n\t\"liability_account_id\" text NOT NULL,\n\t\"txn_id\" text,\n\t\"purchased_on\" text NOT NULL,\n\t\"months\" integer NOT NULL,\n\t\"total_minor\" bigint NOT NULL,\n\t\"commodity\" text NOT NULL,\n\t\"interest_free\" integer DEFAULT 1 NOT NULL,\n\t\"label\" text,\n\tCONSTRAINT \"installment_months_positive\" CHECK (\"months\" >= 1),\n\tCONSTRAINT \"installment_total_positive\" CHECK (\"total_minor\" > 0),\n\tCONSTRAINT \"installment_accounts_differ\" CHECK (\"card_account_id\" <> \"liability_account_id\"),\n\tCONSTRAINT \"installment_interest_free_bool\" CHECK (\"interest_free\" IN (0,1))\n);",
      "CREATE TABLE \"installment_row\" (\n\t\"installment_id\" text,\n\t\"seq\" integer,\n\t\"payment_date\" text NOT NULL,\n\t\"principal_minor\" bigint NOT NULL,\n\t\"fee_minor\" bigint DEFAULT 0 NOT NULL,\n\tCONSTRAINT \"installment_row_pkey\" PRIMARY KEY(\"installment_id\",\"seq\"),\n\tCONSTRAINT \"installment_row_seq_positive\" CHECK (\"seq\" >= 1)\n);",
      "CREATE TABLE \"loan\" (\n\t\"account_id\" text PRIMARY KEY,\n\t\"funding_account_id\" text NOT NULL,\n\t\"interest_account_id\" text NOT NULL,\n\t\"principal_minor\" bigint NOT NULL,\n\t\"commodity\" text NOT NULL,\n\t\"annual_rate_text\" text NOT NULL,\n\t\"method\" text NOT NULL,\n\t\"term_months\" integer NOT NULL,\n\t\"first_payment_date\" text NOT NULL,\n\t\"payment_day\" integer NOT NULL,\n\t\"label\" text,\n\tCONSTRAINT \"loan_principal_positive\" CHECK (\"principal_minor\" > 0),\n\tCONSTRAINT \"loan_term_positive\" CHECK (\"term_months\" >= 1),\n\tCONSTRAINT \"loan_method_enum\" CHECK (\"method\" IN ('annuity','equal_principal','bullet','interest_only')),\n\tCONSTRAINT \"loan_payment_day_range\" CHECK (\"payment_day\" = -1 OR \"payment_day\" BETWEEN 1 AND 31),\n\tCONSTRAINT \"loan_accounts_differ\" CHECK (\"account_id\" <> \"funding_account_id\")\n);",
      "CREATE TABLE \"loan_schedule_row\" (\n\t\"loan_id\" text,\n\t\"seq\" integer,\n\t\"due_date\" text NOT NULL,\n\t\"opening_minor\" bigint NOT NULL,\n\t\"principal_minor\" bigint NOT NULL,\n\t\"interest_minor\" bigint NOT NULL,\n\t\"closing_minor\" bigint NOT NULL,\n\tCONSTRAINT \"loan_schedule_row_pkey\" PRIMARY KEY(\"loan_id\",\"seq\"),\n\tCONSTRAINT \"loan_schedule_seq_positive\" CHECK (\"seq\" >= 1)\n);",
      "CREATE TABLE \"period\" (\n\t\"id\" text PRIMARY KEY,\n\t\"grain\" text NOT NULL,\n\t\"start\" text NOT NULL,\n\t\"end\" text NOT NULL,\n\t\"status\" text DEFAULT 'open' NOT NULL,\n\tCONSTRAINT \"period_grain_enum\" CHECK (\"grain\" IN ('day','week','month','quarter','year')),\n\tCONSTRAINT \"period_status_enum\" CHECK (\"status\" IN ('open','closed','locked'))\n);",
      "CREATE TABLE \"posting\" (\n\t\"txn_id\" text,\n\t\"seq\" integer,\n\t\"account_id\" text NOT NULL,\n\t\"units_minor\" bigint NOT NULL,\n\t\"commodity\" text NOT NULL,\n\t\"weight_minor\" bigint NOT NULL,\n\t\"weight_source\" text NOT NULL,\n\t\"fx_rate_text\" text,\n\t\"fx_rate_id\" text,\n\t\"lot_id\" text,\n\t\"kind\" text DEFAULT 'normal' NOT NULL,\n\t\"memo\" text,\n\tCONSTRAINT \"posting_pkey\" PRIMARY KEY(\"txn_id\",\"seq\"),\n\tCONSTRAINT \"posting_weight_source_enum\" CHECK (\"weight_source\" IN ('identity','actual','rate','plug')),\n\tCONSTRAINT \"posting_kind_enum\" CHECK (\"kind\" IN ('normal','fx_revaluation','rounding'))\n);",
      "CREATE TABLE \"recurring\" (\n\t\"id\" text PRIMARY KEY,\n\t\"label\" text NOT NULL,\n\t\"expense_account_id\" text NOT NULL,\n\t\"funding_account_id\" text NOT NULL,\n\t\"amount_minor\" bigint NOT NULL,\n\t\"commodity\" text NOT NULL,\n\t\"cadence_kind\" text NOT NULL,\n\t\"day_of_month\" integer NOT NULL,\n\t\"month\" integer,\n\t\"active_from\" text NOT NULL,\n\t\"active_to\" text,\n\tCONSTRAINT \"recurring_amount_positive\" CHECK (\"amount_minor\" > 0),\n\tCONSTRAINT \"recurring_cadence_enum\" CHECK (\"cadence_kind\" IN ('monthly','yearly')),\n\tCONSTRAINT \"recurring_day_range\" CHECK (\"day_of_month\" = -1 OR \"day_of_month\" BETWEEN 1 AND 31),\n\tCONSTRAINT \"recurring_month_range\" CHECK (\"month\" IS NULL OR \"month\" BETWEEN 1 AND 12),\n\tCONSTRAINT \"recurring_yearly_needs_month\" CHECK (\"cadence_kind\" <> 'yearly' OR \"month\" IS NOT NULL)\n);",
      "CREATE TABLE \"snapshot\" (\n\t\"id\" text PRIMARY KEY,\n\t\"period_id\" text NOT NULL,\n\t\"kind\" text NOT NULL,\n\t\"as_of\" text NOT NULL,\n\t\"created_at\" text NOT NULL,\n\tCONSTRAINT \"snapshot_kind_enum\" CHECK (\"kind\" IN ('close','checkpoint'))\n);",
      "CREATE TABLE \"snapshot_balance\" (\n\t\"snapshot_id\" text,\n\t\"account_id\" text,\n\t\"commodity\" text,\n\t\"units_minor\" bigint NOT NULL,\n\t\"weight_minor\" bigint NOT NULL,\n\t\"period_units_minor\" bigint DEFAULT 0 NOT NULL,\n\t\"period_weight_minor\" bigint DEFAULT 0 NOT NULL,\n\tCONSTRAINT \"snapshot_balance_pkey\" PRIMARY KEY(\"snapshot_id\",\"account_id\",\"commodity\")\n);",
      "CREATE TABLE \"txn\" (\n\t\"id\" text PRIMARY KEY,\n\t\"date\" text NOT NULL,\n\t\"booking_commodity\" text NOT NULL,\n\t\"payee\" text,\n\t\"narration\" text DEFAULT '' NOT NULL,\n\t\"status\" text NOT NULL,\n\t\"system_kind\" text,\n\t\"corrects_txn_id\" text,\n\t\"source_item_id\" text,\n\t\"fx_estimated\" integer DEFAULT 0 NOT NULL,\n\t\"tags_json\" text DEFAULT '[]' NOT NULL,\n\t\"meta_json\" text DEFAULT '{}' NOT NULL,\n\t\"sealed\" integer DEFAULT 0 NOT NULL,\n\t\"reason\" text,\n\t\"created_at\" text NOT NULL,\n\tCONSTRAINT \"txn_status_enum\" CHECK (\"status\" IN ('draft','posted','void','rejected')),\n\tCONSTRAINT \"txn_system_kind_enum\" CHECK (\"system_kind\" IS NULL OR \"system_kind\" IN ('fx_revaluation','closing_entry','opening_balance')),\n\tCONSTRAINT \"txn_fx_estimated_bool\" CHECK (\"fx_estimated\" IN (0,1)),\n\tCONSTRAINT \"txn_sealed_bool\" CHECK (\"sealed\" IN (0,1))\n);",
      "CREATE INDEX \"account_by_code\" ON \"account\" (\"code\");",
      "CREATE UNIQUE INDEX \"balance_assertion_unique\" ON \"balance_assertion\" (\"account_id\",\"as_of\",\"commodity\");",
      "CREATE INDEX \"balance_assertion_by_date\" ON \"balance_assertion\" (\"as_of\");",
      "CREATE UNIQUE INDEX \"fx_rate_unique\" ON \"fx_rate\" (\"as_of\",\"base\",\"quote\",\"source\");",
      "CREATE INDEX \"ingest_item_by_dedupe\" ON \"ingest_item\" (\"dedupe_key\");",
      "CREATE INDEX \"ingest_item_by_batch\" ON \"ingest_item\" (\"batch_id\");",
      "CREATE INDEX \"installment_by_card\" ON \"installment\" (\"card_account_id\");",
      "CREATE INDEX \"installment_row_by_date\" ON \"installment_row\" (\"payment_date\");",
      "CREATE INDEX \"loan_schedule_by_date\" ON \"loan_schedule_row\" (\"due_date\");",
      "CREATE UNIQUE INDEX \"period_grain_start\" ON \"period\" (\"grain\",\"start\");",
      "CREATE INDEX \"posting_by_account\" ON \"posting\" (\"account_id\");",
      "CREATE INDEX \"recurring_by_funding\" ON \"recurring\" (\"funding_account_id\");",
      "CREATE UNIQUE INDEX \"snapshot_unique\" ON \"snapshot\" (\"period_id\",\"kind\");",
      "CREATE INDEX \"txn_by_date\" ON \"txn\" (\"date\",\"id\");",
      "CREATE INDEX \"txn_by_status\" ON \"txn\" (\"status\");",
      "ALTER TABLE \"account\" ADD CONSTRAINT \"account_commodity_commodity_code_fkey\" FOREIGN KEY (\"commodity\") REFERENCES \"commodity\"(\"code\");",
      "ALTER TABLE \"balance_assertion\" ADD CONSTRAINT \"balance_assertion_account_id_account_id_fkey\" FOREIGN KEY (\"account_id\") REFERENCES \"account\"(\"id\");",
      "ALTER TABLE \"balance_assertion\" ADD CONSTRAINT \"balance_assertion_commodity_commodity_code_fkey\" FOREIGN KEY (\"commodity\") REFERENCES \"commodity\"(\"code\");",
      "ALTER TABLE \"book\" ADD CONSTRAINT \"book_functional_currency_commodity_code_fkey\" FOREIGN KEY (\"functional_currency\") REFERENCES \"commodity\"(\"code\");",
      "ALTER TABLE \"card\" ADD CONSTRAINT \"card_account_id_account_id_fkey\" FOREIGN KEY (\"account_id\") REFERENCES \"account\"(\"id\");",
      "ALTER TABLE \"card\" ADD CONSTRAINT \"card_funding_account_id_account_id_fkey\" FOREIGN KEY (\"funding_account_id\") REFERENCES \"account\"(\"id\");",
      "ALTER TABLE \"fx_rate\" ADD CONSTRAINT \"fx_rate_base_commodity_code_fkey\" FOREIGN KEY (\"base\") REFERENCES \"commodity\"(\"code\");",
      "ALTER TABLE \"fx_rate\" ADD CONSTRAINT \"fx_rate_quote_commodity_code_fkey\" FOREIGN KEY (\"quote\") REFERENCES \"commodity\"(\"code\");",
      "ALTER TABLE \"ingest_item\" ADD CONSTRAINT \"ingest_item_batch_id_ingest_batch_id_fkey\" FOREIGN KEY (\"batch_id\") REFERENCES \"ingest_batch\"(\"id\") ON DELETE CASCADE;",
      "ALTER TABLE \"ingest_item\" ADD CONSTRAINT \"ingest_item_txn_id_txn_id_fkey\" FOREIGN KEY (\"txn_id\") REFERENCES \"txn\"(\"id\");",
      "ALTER TABLE \"installment\" ADD CONSTRAINT \"installment_card_account_id_account_id_fkey\" FOREIGN KEY (\"card_account_id\") REFERENCES \"account\"(\"id\");",
      "ALTER TABLE \"installment\" ADD CONSTRAINT \"installment_liability_account_id_account_id_fkey\" FOREIGN KEY (\"liability_account_id\") REFERENCES \"account\"(\"id\");",
      "ALTER TABLE \"installment\" ADD CONSTRAINT \"installment_txn_id_txn_id_fkey\" FOREIGN KEY (\"txn_id\") REFERENCES \"txn\"(\"id\");",
      "ALTER TABLE \"installment\" ADD CONSTRAINT \"installment_commodity_commodity_code_fkey\" FOREIGN KEY (\"commodity\") REFERENCES \"commodity\"(\"code\");",
      "ALTER TABLE \"installment_row\" ADD CONSTRAINT \"installment_row_installment_id_installment_id_fkey\" FOREIGN KEY (\"installment_id\") REFERENCES \"installment\"(\"id\") ON DELETE CASCADE;",
      "ALTER TABLE \"loan\" ADD CONSTRAINT \"loan_account_id_account_id_fkey\" FOREIGN KEY (\"account_id\") REFERENCES \"account\"(\"id\");",
      "ALTER TABLE \"loan\" ADD CONSTRAINT \"loan_funding_account_id_account_id_fkey\" FOREIGN KEY (\"funding_account_id\") REFERENCES \"account\"(\"id\");",
      "ALTER TABLE \"loan\" ADD CONSTRAINT \"loan_interest_account_id_account_id_fkey\" FOREIGN KEY (\"interest_account_id\") REFERENCES \"account\"(\"id\");",
      "ALTER TABLE \"loan\" ADD CONSTRAINT \"loan_commodity_commodity_code_fkey\" FOREIGN KEY (\"commodity\") REFERENCES \"commodity\"(\"code\");",
      "ALTER TABLE \"loan_schedule_row\" ADD CONSTRAINT \"loan_schedule_row_loan_id_loan_account_id_fkey\" FOREIGN KEY (\"loan_id\") REFERENCES \"loan\"(\"account_id\") ON DELETE CASCADE;",
      "ALTER TABLE \"posting\" ADD CONSTRAINT \"posting_txn_id_txn_id_fkey\" FOREIGN KEY (\"txn_id\") REFERENCES \"txn\"(\"id\");",
      "ALTER TABLE \"posting\" ADD CONSTRAINT \"posting_account_id_account_id_fkey\" FOREIGN KEY (\"account_id\") REFERENCES \"account\"(\"id\");",
      "ALTER TABLE \"posting\" ADD CONSTRAINT \"posting_commodity_commodity_code_fkey\" FOREIGN KEY (\"commodity\") REFERENCES \"commodity\"(\"code\");",
      "ALTER TABLE \"recurring\" ADD CONSTRAINT \"recurring_expense_account_id_account_id_fkey\" FOREIGN KEY (\"expense_account_id\") REFERENCES \"account\"(\"id\");",
      "ALTER TABLE \"recurring\" ADD CONSTRAINT \"recurring_funding_account_id_account_id_fkey\" FOREIGN KEY (\"funding_account_id\") REFERENCES \"account\"(\"id\");",
      "ALTER TABLE \"recurring\" ADD CONSTRAINT \"recurring_commodity_commodity_code_fkey\" FOREIGN KEY (\"commodity\") REFERENCES \"commodity\"(\"code\");",
      "ALTER TABLE \"snapshot\" ADD CONSTRAINT \"snapshot_period_id_period_id_fkey\" FOREIGN KEY (\"period_id\") REFERENCES \"period\"(\"id\");",
      "ALTER TABLE \"snapshot_balance\" ADD CONSTRAINT \"snapshot_balance_snapshot_id_snapshot_id_fkey\" FOREIGN KEY (\"snapshot_id\") REFERENCES \"snapshot\"(\"id\") ON DELETE CASCADE;",
      "ALTER TABLE \"snapshot_balance\" ADD CONSTRAINT \"snapshot_balance_account_id_account_id_fkey\" FOREIGN KEY (\"account_id\") REFERENCES \"account\"(\"id\");",
      "ALTER TABLE \"snapshot_balance\" ADD CONSTRAINT \"snapshot_balance_commodity_commodity_code_fkey\" FOREIGN KEY (\"commodity\") REFERENCES \"commodity\"(\"code\");",
      "ALTER TABLE \"txn\" ADD CONSTRAINT \"txn_booking_commodity_commodity_code_fkey\" FOREIGN KEY (\"booking_commodity\") REFERENCES \"commodity\"(\"code\");"
    ]
  },
  {
    "name": "20260717115212_invariant_triggers",
    "hash": "46e614470fb4400d79ddc3b863a7d94a08ec170ecba29432c34fc876200b8ef9",
    "statements": [
      "-- Ring 3: invariants enforced at rest — the Postgres dialect.\n--\n-- Same invariants as SQLite's, and NOT the same SQL. SQLite says\n-- `SELECT RAISE(ABORT, '…') WHERE <bad>`; Postgres needs a plpgsql function\n-- returning a trigger, with `RAISE EXCEPTION`, attached by CREATE TRIGGER. There\n-- is no toolchain that makes these one file — this is what ADR-005 means when it\n-- says the dialects differ and the port boundary is the thing that spans them.\n--\n-- drizzle-kit models no triggers in either dialect, so both are hand-written\n-- `generate --custom` migrations.\n--\n-- WARNING, as in SQLite: any migration that recreates txn, posting, account,\n-- commodity or audit_log must re-create these. Postgres keeps triggers across an\n-- ALTER, unlike SQLite's table-recreate strategy, so this is less likely here —\n-- but a DROP/CREATE still takes them.\n\nCREATE OR REPLACE FUNCTION holiday_txn_seal_requires_balance() RETURNS trigger AS $$\nDECLARE\n  leg_count integer;\n  residual  bigint;\nBEGIN\n  IF NEW.sealed = 1 AND OLD.sealed = 0 THEN\n    SELECT COUNT(*), COALESCE(SUM(weight_minor), 0) INTO leg_count, residual\n      FROM posting WHERE txn_id = NEW.id;\n    IF leg_count < 2 THEN\n      RAISE EXCEPTION 'holiday: transaction has fewer than two postings';\n    END IF;\n    IF residual <> 0 THEN\n      RAISE EXCEPTION 'holiday: unbalanced transaction — postings must sum to exactly zero (residual %)', residual;\n    END IF;\n  END IF;\n  RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql;",
      "CREATE TRIGGER txn_seal_requires_balance\nBEFORE UPDATE OF sealed ON txn\nFOR EACH ROW EXECUTE FUNCTION holiday_txn_seal_requires_balance();",
      "CREATE OR REPLACE FUNCTION holiday_posting_guards() RETURNS trigger AS $$\nDECLARE\n  acct_commodity text;\n  acct_placeholder integer;\n  booking text;\n  is_sealed integer;\nBEGIN\n  SELECT commodity, placeholder INTO acct_commodity, acct_placeholder\n    FROM account WHERE id = NEW.account_id;\n\n  IF acct_placeholder = 1 THEN\n    RAISE EXCEPTION 'holiday: cannot post to a placeholder account';\n  END IF;\n\n  -- The most likely real error in the whole system: the vision model reads '$'\n  -- as '₩' and posts USD into a KRW-only account. This is where it dies.\n  IF acct_commodity IS NOT NULL AND acct_commodity <> NEW.commodity THEN\n    RAISE EXCEPTION 'holiday: posting commodity % does not match the account''s declared %',\n      NEW.commodity, acct_commodity;\n  END IF;\n\n  SELECT booking_commodity, sealed INTO booking, is_sealed FROM txn WHERE id = NEW.txn_id;\n\n  IF NEW.commodity = booking AND NEW.weight_minor <> NEW.units_minor THEN\n    RAISE EXCEPTION 'holiday: a posting already in the booking commodity must have weight = units';\n  END IF;\n\n  -- The journal is append-only. Once sealed, postings are facts.\n  IF is_sealed = 1 THEN\n    RAISE EXCEPTION 'holiday: cannot add a posting to a sealed transaction — write a correction instead';\n  END IF;\n\n  RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql;",
      "CREATE TRIGGER posting_guards\nBEFORE INSERT ON posting\nFOR EACH ROW EXECUTE FUNCTION holiday_posting_guards();",
      "CREATE OR REPLACE FUNCTION holiday_posting_immutable() RETURNS trigger AS $$\nDECLARE\n  is_sealed integer;\nBEGIN\n  SELECT sealed INTO is_sealed FROM txn WHERE id = OLD.txn_id;\n  IF is_sealed = 1 THEN\n    RAISE EXCEPTION 'holiday: postings of a sealed transaction are immutable — write a correction instead';\n  END IF;\n  RETURN OLD;\nEND;\n$$ LANGUAGE plpgsql;",
      "CREATE TRIGGER posting_immutable_update\nBEFORE UPDATE ON posting\nFOR EACH ROW EXECUTE FUNCTION holiday_posting_immutable();",
      "CREATE TRIGGER posting_immutable_delete\nBEFORE DELETE ON posting\nFOR EACH ROW EXECUTE FUNCTION holiday_posting_immutable();",
      "CREATE OR REPLACE FUNCTION holiday_txn_never_unseals() RETURNS trigger AS $$\nBEGIN\n  IF OLD.sealed = 1 AND NEW.sealed = 0 THEN\n    RAISE EXCEPTION 'holiday: a sealed transaction cannot be unsealed';\n  END IF;\n  RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql;",
      "CREATE TRIGGER txn_never_unseals\nBEFORE UPDATE OF sealed ON txn\nFOR EACH ROW EXECUTE FUNCTION holiday_txn_never_unseals();",
      "-- An exponent change silently rescales every amount of that commodity.\nCREATE OR REPLACE FUNCTION holiday_commodity_exponent_immutable() RETURNS trigger AS $$\nBEGIN\n  IF OLD.exponent <> NEW.exponent AND EXISTS (SELECT 1 FROM posting WHERE commodity = OLD.code) THEN\n    RAISE EXCEPTION 'holiday: cannot change the exponent of a commodity that has postings';\n  END IF;\n  RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql;",
      "CREATE TRIGGER commodity_exponent_immutable\nBEFORE UPDATE OF exponent ON commodity\nFOR EACH ROW EXECUTE FUNCTION holiday_commodity_exponent_immutable();",
      "-- An audit log you can quietly edit is decoration.\nCREATE OR REPLACE FUNCTION holiday_audit_log_append_only() RETURNS trigger AS $$\nBEGIN\n  RAISE EXCEPTION 'holiday: the audit log is append-only';\nEND;\n$$ LANGUAGE plpgsql;",
      "CREATE TRIGGER audit_log_immutable_update\nBEFORE UPDATE ON audit_log\nFOR EACH ROW EXECUTE FUNCTION holiday_audit_log_append_only();",
      "CREATE TRIGGER audit_log_immutable_delete\nBEFORE DELETE ON audit_log\nFOR EACH ROW EXECUTE FUNCTION holiday_audit_log_append_only();"
    ]
  }
];
