/**
 * Inlines drizzle-kit's generated SQL into a TypeScript module.
 *
 * Drizzle's own `migrate()` calls `readMigrationFiles`, which is straight
 * `node:fs` against a migrations folder next to your app. The CLI here ships as a
 * single self-contained .mjs inside a Claude Code plugin — there is no folder
 * next to it and no install step to create one — so that path is unusable. The
 * SQL becomes a string constant at build time instead.
 *
 * The hash is sha256 of the raw file, which is the same thing Drizzle records in
 * `__drizzle_migrations`. It is the good idea worth taking from Drizzle: it makes
 * "migrations are append-only" enforceable rather than a comment. Edit a migration
 * that has already run and the next open fails loudly instead of silently
 * diverging from every other copy of the ledger.
 *
 * Run: pnpm --filter @holiday/store-postgres run migrations:inline
 */
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const PKG = resolve(import.meta.dirname, '..');
const MIGRATIONS_DIR = join(PKG, 'migrations');
const OUT = join(PKG, 'src', 'migrations.generated.ts');

const BREAKPOINT = '--> statement-breakpoint';

function main(): void {
  if (!existsSync(MIGRATIONS_DIR)) throw new Error(`no migrations folder at ${MIGRATIONS_DIR}`);

  // Folder names are timestamp-prefixed, so lexical order IS chronological order.
  // Ordering is the whole contract of a migration list; do not sort by anything else.
  const dirs = readdirSync(MIGRATIONS_DIR)
    .filter((d) => existsSync(join(MIGRATIONS_DIR, d, 'migration.sql')))
    .sort();

  if (dirs.length === 0) throw new Error('no migrations found — did drizzle-kit generate run?');

  const entries = dirs.map((name) => {
    const raw = readFileSync(join(MIGRATIONS_DIR, name, 'migration.sql'), 'utf8');
    const hash = createHash('sha256').update(raw).digest('hex');
    const statements = raw
      .split(BREAKPOINT)
      .map((s) => s.trim())
      .filter((s) => s.length > 0 && !/^(--[^\n]*\n?)+$/.test(s));
    return { name, hash, statements };
  });

  const body = `// GENERATED by scripts/inline-migrations.ts — do not edit.
//
// Source of truth is src/schema.drizzle.ts (tables, via drizzle-kit generate) plus
// the hand-written custom migrations under migrations/ (triggers, which drizzle-kit
// does not model). Regenerate with:
//
//   pnpm --filter @holiday/store-postgres run migrations:build
//
// This exists because the CLI ships as one self-contained file: Drizzle's migrate()
// reads .sql off disk at runtime, and there is no disk to read next to a bundled
// plugin binary.

export interface InlinedMigration {
  readonly name: string;
  /** sha256 of the raw migration.sql. Editing an applied migration is detected. */
  readonly hash: string;
  readonly statements: readonly string[];
}

export const MIGRATIONS: readonly InlinedMigration[] = ${JSON.stringify(entries, null, 2)};
`;

  writeFileSync(OUT, body);
  console.log(`✓ inlined ${entries.length} migration(s) → src/migrations.generated.ts`);
  for (const e of entries) {
    console.log(`  ${e.name.padEnd(34)} ${e.statements.length} statement(s)  ${e.hash.slice(0, 12)}…`);
  }
}

main();
